
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brzphvglwoizpwxvphvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyenBodmdsd29penB3eHZwaHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3OTc2ODAsImV4cCI6MjA2MzM3MzY4MH0.tByVMsLhE3K6D2QEm3jWFy3o-rJ21PDWCJmKoeIzCSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
